In [1]:
import pandas as pd, numpy as np 

def read_csv(file, names=[]):
    index_names = ['unit_number', 'time_cycles']
    setting_names = ['setting_1', 'setting_2', 'setting_3']
    sensor_names = ['s_{}'.format(i+1) for i in range(0,21)]
    col_names = index_names + setting_names + sensor_names
    df = pd.read_csv(f'CMAPSSData/{file}' ,sep='\s+',header=None,index_col=False,names=col_names if names == [] else names)
    return df

test = read_csv("test_FD001.txt")

<>:8: SyntaxWarning: invalid escape sequence '\s'
<>:8: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_3790766/1641612385.py:8: SyntaxWarning: invalid escape sequence '\s'
  df = pd.read_csv(f'CMAPSSData/{file}' ,sep='\s+',header=None,index_col=False,names=col_names if names == [] else names)

In [40]:
norm_test = test[(test.time_cycles <= 30)].copy()
norm_test["Fault"] = 0
norm_test

,unit_number,time_cycles,setting_1,setting_2,setting_3,s_1,s_2,s_3,s_4,s_5,...,s_13,s_14,s_15,s_16,s_17,s_18,s_19,s_20,s_21,Fault
0,1,1,0.0023,0.0003,100.0,518.67,643.02,1585.29,1398.21,14.62,...,2388.03,8125.55,8.4052,0.03,392,2388,100.0,38.86,23.3735,0
1,1,2,-0.0027,-0.0003,100.0,518.67,641.71,1588.45,1395.42,14.62,...,2388.06,8139.62,8.3803,0.03,393,2388,100.0,39.02,23.3916,0
2,1,3,0.0003,0.0001,100.0,518.67,642.46,1586.94,1401.34,14.62,...,2388.03,8130.10,8.4441,0.03,393,2388,100.0,39.08,23.4166,0
3,1,4,0.0042,0.0000,100.0,518.67,642.44,1584.12,1406.42,14.62,...,2388.05,8132.90,8.3917,0.03,391,2388,100.0,39.00,23.3737,0
4,1,5,0.0014,0.0000,100.0,518.67,642.51,1587.19,1401.92,14.62,...,2388.03,8129.54,8.4031,0.03,390,2388,100.0,38.99,23.4130,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12923,100,26,-0.0010,-0.0002,100.0,518.67,641.94,1587.41,1399.99,14.62,...,2388.03,8140.44,8.3950,0.03,392,2388,100.0,39.25,23.4504,0
12924,100,27,-0.0009,-0.0002,100.0,518.67,642.26,1585.74,1406.69,14.62,...,2388.02,8144.31,8.3870,0.03,391,2388,100.0,39.11,23.3978,0
12925,100,28,-0.0023,0.0002,100.0,518.67,641.92,1582.94,1396.12,14.62,...,2388.05,8137.18,8.4518,0.03,391,2388,100.0,39.06,23.3690,0
12926,100,29,-0.0014,0.0005,100.0,518.67,642.50,1581.81,1402.35,14.62,...,2388.01,8137.96,8.4153,0.03,392,2388,100.0,38.90,23.4324,0
12927,100,30,-0.0008,-0.0004,100.0,518.67,642.28,1582.86,1396.39,14.62,...,2388.01,8137.14,8.4146,0.03,392,2388,100.0,39.10,23.3772,0

In [42]:
max_cycles = test.groupby("unit_number")["time_cycles"].max()
valid_engines = max_cycles[max_cycles > 60].index
fault_start = max_cycles[valid_engines] - 29
fault_test = test[
    test["unit_number"].isin(valid_engines) &                        # engine must qualify
    (test["time_cycles"] >= test["unit_number"].map(fault_start))    # cycle >= max - 29
].copy()
fault_test["Fault"] = 1
fault_test

,unit_number,time_cycles,setting_1,setting_2,setting_3,s_1,s_2,s_3,s_4,s_5,...,s_13,s_14,s_15,s_16,s_17,s_18,s_19,s_20,s_21,Fault
176,3,97,-0.0073,-0.0003,100.0,518.67,642.86,1588.90,1408.72,14.62,...,2388.16,8128.39,8.4480,0.03,392,2388,100.0,38.82,23.2457,1
177,3,98,-0.0015,0.0002,100.0,518.67,642.46,1596.30,1409.74,14.62,...,2388.16,8129.69,8.4624,0.03,394,2388,100.0,38.99,23.2503,1
178,3,99,-0.0007,0.0003,100.0,518.67,642.71,1594.95,1409.94,14.62,...,2388.19,8129.59,8.4535,0.03,393,2388,100.0,38.94,23.2226,1
179,3,100,0.0007,0.0004,100.0,518.67,642.53,1600.07,1412.83,14.62,...,2388.11,8127.41,8.4299,0.03,394,2388,100.0,38.65,23.3360,1
180,3,101,0.0019,0.0000,100.0,518.67,642.44,1586.97,1408.99,14.62,...,2388.12,8123.97,8.4394,0.03,393,2388,100.0,38.73,23.1899,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13091,100,194,0.0049,0.0000,100.0,518.67,643.24,1599.45,1415.79,14.62,...,2388.00,8213.28,8.4715,0.03,394,2388,100.0,38.65,23.1974,1
13092,100,195,-0.0011,-0.0001,100.0,518.67,643.22,1595.69,1422.05,14.62,...,2388.09,8210.85,8.4512,0.03,395,2388,100.0,38.57,23.2771,1
13093,100,196,-0.0006,-0.0003,100.0,518.67,643.44,1593.15,1406.82,14.62,...,2388.04,8217.24,8.4569,0.03,395,2388,100.0,38.62,23.2051,1
13094,100,197,-0.0038,0.0001,100.0,518.67,643.26,1594.99,1419.36,14.62,...,2388.08,8220.48,8.4711,0.03,395,2388,100.0,38.66,23.2699,1
13095,100,198,0.0013,0.0003,100.0,518.67,642.95,1601.62,1424.99,14.62,...,2388.05,8214.64,8.4903,0.03,396,2388,100.0,38.70,23.1855,1

In [44]:
test_combined = pd.concat([norm_test, fault_test])
test_combined

,unit_number,time_cycles,setting_1,setting_2,setting_3,s_1,s_2,s_3,s_4,s_5,...,s_13,s_14,s_15,s_16,s_17,s_18,s_19,s_20,s_21,Fault
0,1,1,0.0023,0.0003,100.0,518.67,643.02,1585.29,1398.21,14.62,...,2388.03,8125.55,8.4052,0.03,392,2388,100.0,38.86,23.3735,0
1,1,2,-0.0027,-0.0003,100.0,518.67,641.71,1588.45,1395.42,14.62,...,2388.06,8139.62,8.3803,0.03,393,2388,100.0,39.02,23.3916,0
2,1,3,0.0003,0.0001,100.0,518.67,642.46,1586.94,1401.34,14.62,...,2388.03,8130.10,8.4441,0.03,393,2388,100.0,39.08,23.4166,0
3,1,4,0.0042,0.0000,100.0,518.67,642.44,1584.12,1406.42,14.62,...,2388.05,8132.90,8.3917,0.03,391,2388,100.0,39.00,23.3737,0
4,1,5,0.0014,0.0000,100.0,518.67,642.51,1587.19,1401.92,14.62,...,2388.03,8129.54,8.4031,0.03,390,2388,100.0,38.99,23.4130,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13091,100,194,0.0049,0.0000,100.0,518.67,643.24,1599.45,1415.79,14.62,...,2388.00,8213.28,8.4715,0.03,394,2388,100.0,38.65,23.1974,1
13092,100,195,-0.0011,-0.0001,100.0,518.67,643.22,1595.69,1422.05,14.62,...,2388.09,8210.85,8.4512,0.03,395,2388,100.0,38.57,23.2771,1
13093,100,196,-0.0006,-0.0003,100.0,518.67,643.44,1593.15,1406.82,14.62,...,2388.04,8217.24,8.4569,0.03,395,2388,100.0,38.62,23.2051,1
13094,100,197,-0.0038,0.0001,100.0,518.67,643.26,1594.99,1419.36,14.62,...,2388.08,8220.48,8.4711,0.03,395,2388,100.0,38.66,23.2699,1
13095,100,198,0.0013,0.0003,100.0,518.67,642.95,1601.62,1424.99,14.62,...,2388.05,8214.64,8.4903,0.03,396,2388,100.0,38.70,23.1855,1

In [46]:
test_combined.to_csv("csv/test_FD001.csv", index=False)